name: generate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: [ubuntu-latest]
    timeout-minutes: 8
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: ⚙️ Run Golang code generate
        shell: bash
        run: |
          set -xe
          make tools generate
          [[ -z "$(git status -s)" ]]
